import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chronicle",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-background text-foreground">
        <main className="flex h-screen overflow-hidden">
          {user !== null ? (
            <div className="flex-none h-full">
              <Sidebar />
            </div>
          ) : null}

          <div className="flex-1 h-full overflow-y-auto md:ml-[var(--sidebar-width)]">
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
