-- habits

create table habits(
  h_id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  h_name text check not null,
  h_question text check not null,
  h_note text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table habits enable row level security;

create policy "Users can create habits." on habits for
insert with check (auth.uid() = user_id);
create policy "Users can view their own habits." on habits for
select using ((select auth.uid()) = user_id);
create policy "Users can update their own habits." on habits for
update using ((select auth.uid()) = user_id);
create policy "Users can delete their own habits." on habits for
delete using ((select auth.uid()) = user_id);